### PR TITLE
Add support for safe concurrent MySQL calls and MariaDB

### PR DESCRIPTION
**Pull request by 3noch**
I didn't do any of the work for this, but I'm happy to make edits as you see fit to make it ready to merge.

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Is there a chance this can be merged?

**Comment by 3noch** [comment]
Not much of one, unless someone can convince @bos to spend time on it, or make them a contributor. Unfortunately I'm no longer in a place where I use MySQL.

**Comment by massimo-zaniboni** [comment]
I'm using this branch in production, and I confirm it solved all my problems in case of multiple threads opening distinct connections to the same database.

**Comment by 3noch** [comment]
Awesome. @bos?

**Comment by paul-rouse** [comment]
I am inclined to merge this, but, before I do, does anyone have any concerns?

**Comment by massimo-zaniboni** [comment]
I'm the same of 27 July message. I want to be more informative: I'm using the branch for rating millions of VoIP calls. I tested it on many instances/servers of my customers. Records are deleted, rerated, reinserted in blocks, every time there are changes of configurations. So it is not an append-only application, and I have some strees test code.

I converted few instances from an old version rating calls with PHP code to the new version using Haskell code, running them in parallel for some months. The application behaviour is well tested internally, and externally, because VoIP calls costs are double checked with the monthly invoices of service providers.

So for me it is rock-solid. :-)

**Comment by 3noch** [comment]
Wow nice. I know @feuerbach is/was using these changes in production with success.

**Comment by paul-rouse** [comment]
Thank you, that is very helpful.  I'm just being super cautious, having only just taken over maintenance!

**Comment by paul-rouse** [comment]
Thanks everyone!  I'll try this in a real application, and release in a few days.

**Comment by 3noch** [comment]
@paul-rouse 2 years of waiting and it's finally done!

**Pull request merged**
