### PR TITLE
Make connection finalizer thread safe

### PR DESCRIPTION
**Pull request by enolan**

### CODE REVIEW

**Comment by paul-rouse** [comment]
As it stands this causes breakage when the threaded RTS is not being used - the tests fail for this reason.

Also, I am not clear why you need to do this.  You are modifying a function which is simply returned to the caller as part of the API, so under what circumstances can it be called without the developer being in control of threading?

**Comment by enolan** [comment]
The `realClose` function runs when the `connFP` inside the `Connection` returned is garbage collected, via the `ForeignPtr`. It doesn't do anything if the developer already closed the connection though. I didn't realize `runInBoundThread` didn't work in the non-threaded RTS, I'll look into that.

**Comment by paul-rouse** [comment]
My mistake - my eye was consistently skipping over the `newForeignPtr` line!

I think it would be better to limit the change to the use as a finalizer, and not change the function returned in the `Connection`?

BTW, you need to test for a threaded RTS using `rtsSupportsBoundThreads`.

**Comment by enolan** [comment]
Fixed. Something is broken with Homebrew on the OS X Travis build.

**Comment by aniketd** [comment]
@paul-rouse is the code good to be merged as it stands now? Are the CI failures blocking this from being merged? I would like to help getting this merged and released.

**Comment by paul-rouse** [comment]
Yes, I think I probably was waiting for a clean test, but it does look as if it's simply the test which is broken.  I'll merge it, and see how the tests run now.

**Comment by aniketd** [comment]
Thanks @paul-rouse :+1: :smiley:

**Pull request merged**
