### PR TITLE
Add a Semigroup instance

### PR DESCRIPTION
**Pull request by k-bx**

### CODE REVIEW

**Comment by paul-rouse** [comment]
Semigroups wasn't in base until 4.9.  I think we should still support GHC7.10/lts-6 for a while, so the cabal file needs a dependency on `semigroups` conditional on ghc < 8. (I was planning on dropping lts-2 soon.)

**Comment by k-bx** [comment]
Yeah, definitely a WIP until Travis is passing at least

**Comment by k-bx** [comment]
@paul-rouse should be good to go

**Comment by paul-rouse** [comment]
Thanks, and sorry for the delay (work pressures...)

**Pull request merged**
